// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: autoid.proto

package autoid

import (
	"context"
	"fmt"
	"io"
	"math"
	math_bits "math/bits"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	apipb "github.com/pingcap/kvproto/pkg/apipb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AutoIDRequest struct {
	DbID       int64  `protobuf:"varint,1,opt,name=dbID,proto3" json:"dbID,omitempty"`
	TblID      int64  `protobuf:"varint,2,opt,name=tblID,proto3" json:"tblID,omitempty"`
	IsUnsigned bool   `protobuf:"varint,3,opt,name=isUnsigned,proto3" json:"isUnsigned,omitempty"`
	N          uint64 `protobuf:"varint,4,opt,name=n,proto3" json:"n,omitempty"`
	Increment  int64  `protobuf:"varint,5,opt,name=increment,proto3" json:"increment,omitempty"`
	Offset     int64  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	// Types that are valid to be assigned to Keyspace:
	//	*AutoIDRequest_KeyspaceID
	//	*AutoIDRequest_KeyspaceIdentity
	Keyspace isAutoIDRequest_Keyspace `protobuf_oneof:"keyspace"`
}

func (m *AutoIDRequest) Reset()         { *m = AutoIDRequest{} }
func (m *AutoIDRequest) String() string { return proto.CompactTextString(m) }
func (*AutoIDRequest) ProtoMessage()    {}
func (*AutoIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81e5bb779eac45f, []int{0}
}
func (m *AutoIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AutoIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AutoIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AutoIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoIDRequest.Merge(m, src)
}
func (m *AutoIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *AutoIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AutoIDRequest proto.InternalMessageInfo

type isAutoIDRequest_Keyspace interface {
	isAutoIDRequest_Keyspace()
	MarshalTo([]byte) (int, error)
	Size() int
}

type AutoIDRequest_KeyspaceID struct {
	KeyspaceID uint32 `protobuf:"varint,7,opt,name=keyspaceID,proto3,oneof" json:"keyspaceID,omitempty"`
}
type AutoIDRequest_KeyspaceIdentity struct {
	KeyspaceIdentity *apipb.KeyspaceIdentity `protobuf:"bytes,8,opt,name=keyspace_identity,json=keyspaceIdentity,proto3,oneof" json:"keyspace_identity,omitempty"`
}

func (*AutoIDRequest_KeyspaceID) isAutoIDRequest_Keyspace()       {}
func (*AutoIDRequest_KeyspaceIdentity) isAutoIDRequest_Keyspace() {}

func (m *AutoIDRequest) GetKeyspace() isAutoIDRequest_Keyspace {
	if m != nil {
		return m.Keyspace
	}
	return nil
}

func (m *AutoIDRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *AutoIDRequest) GetTblID() int64 {
	if m != nil {
		return m.TblID
	}
	return 0
}

func (m *AutoIDRequest) GetIsUnsigned() bool {
	if m != nil {
		return m.IsUnsigned
	}
	return false
}

func (m *AutoIDRequest) GetN() uint64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *AutoIDRequest) GetIncrement() int64 {
	if m != nil {
		return m.Increment
	}
	return 0
}

func (m *AutoIDRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *AutoIDRequest) GetKeyspaceID() uint32 {
	if x, ok := m.GetKeyspace().(*AutoIDRequest_KeyspaceID); ok {
		return x.KeyspaceID
	}
	return 0
}

func (m *AutoIDRequest) GetKeyspaceIdentity() *apipb.KeyspaceIdentity {
	if x, ok := m.GetKeyspace().(*AutoIDRequest_KeyspaceIdentity); ok {
		return x.KeyspaceIdentity
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AutoIDRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AutoIDRequest_KeyspaceID)(nil),
		(*AutoIDRequest_KeyspaceIdentity)(nil),
	}
}

type AutoIDResponse struct {
	Min    int64  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max    int64  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Errmsg []byte `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (m *AutoIDResponse) Reset()         { *m = AutoIDResponse{} }
func (m *AutoIDResponse) String() string { return proto.CompactTextString(m) }
func (*AutoIDResponse) ProtoMessage()    {}
func (*AutoIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81e5bb779eac45f, []int{1}
}
func (m *AutoIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AutoIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AutoIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AutoIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoIDResponse.Merge(m, src)
}
func (m *AutoIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *AutoIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AutoIDResponse proto.InternalMessageInfo

func (m *AutoIDResponse) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *AutoIDResponse) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *AutoIDResponse) GetErrmsg() []byte {
	if m != nil {
		return m.Errmsg
	}
	return nil
}

type RebaseRequest struct {
	DbID       int64 `protobuf:"varint,1,opt,name=dbID,proto3" json:"dbID,omitempty"`
	TblID      int64 `protobuf:"varint,2,opt,name=tblID,proto3" json:"tblID,omitempty"`
	IsUnsigned bool  `protobuf:"varint,3,opt,name=isUnsigned,proto3" json:"isUnsigned,omitempty"`
	Base       int64 `protobuf:"varint,4,opt,name=base,proto3" json:"base,omitempty"`
	Force      bool  `protobuf:"varint,5,opt,name=force,proto3" json:"force,omitempty"`
	// Types that are valid to be assigned to Keyspace:
	//	*RebaseRequest_KeyspaceID
	//	*RebaseRequest_KeyspaceIdentity
	Keyspace isRebaseRequest_Keyspace `protobuf_oneof:"keyspace"`
}

func (m *RebaseRequest) Reset()         { *m = RebaseRequest{} }
func (m *RebaseRequest) String() string { return proto.CompactTextString(m) }
func (*RebaseRequest) ProtoMessage()    {}
func (*RebaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81e5bb779eac45f, []int{2}
}
func (m *RebaseRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RebaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RebaseRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RebaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebaseRequest.Merge(m, src)
}
func (m *RebaseRequest) XXX_Size() int {
	return m.Size()
}
func (m *RebaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RebaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RebaseRequest proto.InternalMessageInfo

type isRebaseRequest_Keyspace interface {
	isRebaseRequest_Keyspace()
	MarshalTo([]byte) (int, error)
	Size() int
}

type RebaseRequest_KeyspaceID struct {
	KeyspaceID uint32 `protobuf:"varint,6,opt,name=keyspaceID,proto3,oneof" json:"keyspaceID,omitempty"`
}
type RebaseRequest_KeyspaceIdentity struct {
	KeyspaceIdentity *apipb.KeyspaceIdentity `protobuf:"bytes,7,opt,name=keyspace_identity,json=keyspaceIdentity,proto3,oneof" json:"keyspace_identity,omitempty"`
}

func (*RebaseRequest_KeyspaceID) isRebaseRequest_Keyspace()       {}
func (*RebaseRequest_KeyspaceIdentity) isRebaseRequest_Keyspace() {}

func (m *RebaseRequest) GetKeyspace() isRebaseRequest_Keyspace {
	if m != nil {
		return m.Keyspace
	}
	return nil
}

func (m *RebaseRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *RebaseRequest) GetTblID() int64 {
	if m != nil {
		return m.TblID
	}
	return 0
}

func (m *RebaseRequest) GetIsUnsigned() bool {
	if m != nil {
		return m.IsUnsigned
	}
	return false
}

func (m *RebaseRequest) GetBase() int64 {
	if m != nil {
		return m.Base
	}
	return 0
}

func (m *RebaseRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *RebaseRequest) GetKeyspaceID() uint32 {
	if x, ok := m.GetKeyspace().(*RebaseRequest_KeyspaceID); ok {
		return x.KeyspaceID
	}
	return 0
}

func (m *RebaseRequest) GetKeyspaceIdentity() *apipb.KeyspaceIdentity {
	if x, ok := m.GetKeyspace().(*RebaseRequest_KeyspaceIdentity); ok {
		return x.KeyspaceIdentity
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RebaseRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RebaseRequest_KeyspaceID)(nil),
		(*RebaseRequest_KeyspaceIdentity)(nil),
	}
}

type RebaseResponse struct {
	Errmsg []byte `protobuf:"bytes,1,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (m *RebaseResponse) Reset()         { *m = RebaseResponse{} }
func (m *RebaseResponse) String() string { return proto.CompactTextString(m) }
func (*RebaseResponse) ProtoMessage()    {}
func (*RebaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81e5bb779eac45f, []int{3}
}
func (m *RebaseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RebaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RebaseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RebaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebaseResponse.Merge(m, src)
}
func (m *RebaseResponse) XXX_Size() int {
	return m.Size()
}
func (m *RebaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RebaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RebaseResponse proto.InternalMessageInfo

func (m *RebaseResponse) GetErrmsg() []byte {
	if m != nil {
		return m.Errmsg
	}
	return nil
}

func init() {
	proto.RegisterType((*AutoIDRequest)(nil), "autoid.AutoIDRequest")
	proto.RegisterType((*AutoIDResponse)(nil), "autoid.AutoIDResponse")
	proto.RegisterType((*RebaseRequest)(nil), "autoid.RebaseRequest")
	proto.RegisterType((*RebaseResponse)(nil), "autoid.RebaseResponse")
}

func init() { proto.RegisterFile("autoid.proto", fileDescriptor_d81e5bb779eac45f) }

var fileDescriptor_d81e5bb779eac45f = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xb1, 0x8e, 0xd3, 0x30,
	0x1c, 0xc6, 0xe3, 0x6b, 0x2f, 0x17, 0xfe, 0x6d, 0x8f, 0x62, 0x1d, 0x47, 0x54, 0x21, 0x2b, 0xca,
	0x94, 0x29, 0x48, 0x65, 0x62, 0x41, 0xba, 0x53, 0x85, 0xae, 0x82, 0xc9, 0x12, 0x33, 0x4a, 0x5a,
	0x37, 0xb2, 0xda, 0xda, 0x21, 0x76, 0x4f, 0xdc, 0x1b, 0x30, 0x22, 0xb1, 0xf0, 0x08, 0x3c, 0x0a,
	0xe3, 0x8d, 0x37, 0xa2, 0xf6, 0x29, 0xd8, 0x50, 0x6c, 0x47, 0x69, 0x3b, 0x21, 0x71, 0x53, 0xbf,
	0xef, 0xe7, 0xda, 0x8e, 0x7f, 0x71, 0xa0, 0x9f, 0x6d, 0xb4, 0xe4, 0xf3, 0xb4, 0xac, 0xa4, 0x96,
	0xd8, 0xb7, 0x6d, 0xd4, 0xcb, 0x4a, 0x5e, 0xe6, 0x16, 0x8e, 0x2e, 0x0a, 0x59, 0x48, 0x13, 0x5f,
	0xd5, 0xc9, 0xd1, 0xa7, 0xd5, 0x46, 0x69, 0x13, 0x2d, 0x88, 0xbf, 0x9f, 0xc0, 0xe0, 0x6a, 0xa3,
	0xe5, 0x74, 0x42, 0xd9, 0xe7, 0x0d, 0x53, 0x1a, 0x63, 0xe8, 0xce, 0xf3, 0xe9, 0x24, 0x44, 0x11,
	0x4a, 0x3a, 0xd4, 0x64, 0x7c, 0x01, 0xa7, 0x3a, 0x5f, 0x4d, 0x27, 0xe1, 0x89, 0x81, 0xb6, 0x60,
	0x02, 0xc0, 0xd5, 0x47, 0xa1, 0x78, 0x21, 0xd8, 0x3c, 0xec, 0x44, 0x28, 0x09, 0xe8, 0x1e, 0xc1,
	0x7d, 0x40, 0x22, 0xec, 0x46, 0x28, 0xe9, 0x52, 0x24, 0xf0, 0x4b, 0x78, 0xc2, 0xc5, 0xac, 0x62,
	0x6b, 0x26, 0x74, 0x78, 0x6a, 0xd6, 0x69, 0x01, 0xbe, 0x04, 0x5f, 0x2e, 0x16, 0x8a, 0xe9, 0xd0,
	0x37, 0x43, 0xae, 0xe1, 0x08, 0x60, 0xc9, 0xee, 0x54, 0x99, 0xcd, 0xd8, 0x74, 0x12, 0x9e, 0x45,
	0x28, 0x19, 0xdc, 0x78, 0x74, 0x8f, 0xe1, 0x77, 0xf0, 0xac, 0x69, 0x9f, 0xf8, 0x9c, 0x09, 0xcd,
	0xf5, 0x5d, 0x18, 0x44, 0x28, 0xe9, 0x8d, 0x5f, 0xa4, 0xd6, 0xc8, 0xfb, 0xe6, 0xdf, 0x6e, 0xf8,
	0xc6, 0xa3, 0xc3, 0xe5, 0x11, 0xbb, 0x06, 0x08, 0x1a, 0x16, 0x7f, 0x80, 0xf3, 0x46, 0x8a, 0x2a,
	0xa5, 0x50, 0x0c, 0x0f, 0xa1, 0xb3, 0xe6, 0xc2, 0x49, 0xa9, 0xa3, 0x21, 0xd9, 0x17, 0x67, 0xa4,
	0x8e, 0xf5, 0x19, 0x58, 0x55, 0xad, 0x55, 0x61, 0x5c, 0xf4, 0xa9, 0x6b, 0xf1, 0x1f, 0x04, 0x03,
	0xca, 0xf2, 0x4c, 0xb1, 0xc7, 0x77, 0x8c, 0xa1, 0x5b, 0x2f, 0x6c, 0x34, 0x77, 0xa8, 0xc9, 0xf5,
	0x4a, 0x0b, 0x59, 0xcd, 0x98, 0xb1, 0x1c, 0x50, 0x5b, 0x8e, 0x4c, 0xfa, 0xff, 0x6a, 0xf2, 0xec,
	0xff, 0x4c, 0x26, 0x70, 0xde, 0x1c, 0xdd, 0x99, 0x6c, 0x2d, 0xa1, 0x7d, 0x4b, 0xe3, 0xaf, 0x08,
	0x7a, 0x56, 0xfa, 0xd5, 0x6a, 0x25, 0x67, 0xf8, 0x2d, 0xf4, 0x4c, 0xb0, 0x0c, 0x3f, 0x4f, 0xdd,
	0x9d, 0x3f, 0xb8, 0xad, 0xa3, 0xcb, 0x63, 0x6c, 0x77, 0x89, 0x3d, 0xfc, 0x06, 0x7c, 0xbb, 0x73,
	0x3b, 0xf5, 0xe0, 0x25, 0xb4, 0x53, 0x0f, 0x1f, 0x30, 0xf6, 0xae, 0xc7, 0x0f, 0x3f, 0x03, 0xf4,
	0x6b, 0x4b, 0xd0, 0xfd, 0x96, 0xa0, 0xdf, 0x5b, 0x82, 0xbe, 0xed, 0x88, 0xf7, 0x63, 0x47, 0xbc,
	0xfb, 0x1d, 0xf1, 0x1e, 0x76, 0xc4, 0x83, 0xa1, 0xac, 0x8a, 0x54, 0xf3, 0xe5, 0x6d, 0xba, 0xbc,
	0x35, 0x1f, 0x52, 0xee, 0x9b, 0x9f, 0xd7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xd2, 0x48,
	0x04, 0x9b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AutoIDAllocClient is the client API for AutoIDAlloc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AutoIDAllocClient interface {
	AllocAutoID(ctx context.Context, in *AutoIDRequest, opts ...grpc.CallOption) (*AutoIDResponse, error)
	Rebase(ctx context.Context, in *RebaseRequest, opts ...grpc.CallOption) (*RebaseResponse, error)
}

type autoIDAllocClient struct {
	cc *grpc.ClientConn
}

func NewAutoIDAllocClient(cc *grpc.ClientConn) AutoIDAllocClient {
	return &autoIDAllocClient{cc}
}

func (c *autoIDAllocClient) AllocAutoID(ctx context.Context, in *AutoIDRequest, opts ...grpc.CallOption) (*AutoIDResponse, error) {
	out := new(AutoIDResponse)
	err := c.cc.Invoke(ctx, "/autoid.AutoIDAlloc/AllocAutoID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoIDAllocClient) Rebase(ctx context.Context, in *RebaseRequest, opts ...grpc.CallOption) (*RebaseResponse, error) {
	out := new(RebaseResponse)
	err := c.cc.Invoke(ctx, "/autoid.AutoIDAlloc/Rebase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutoIDAllocServer is the server API for AutoIDAlloc service.
type AutoIDAllocServer interface {
	AllocAutoID(context.Context, *AutoIDRequest) (*AutoIDResponse, error)
	Rebase(context.Context, *RebaseRequest) (*RebaseResponse, error)
}

// UnimplementedAutoIDAllocServer can be embedded to have forward compatible implementations.
type UnimplementedAutoIDAllocServer struct {
}

func (*UnimplementedAutoIDAllocServer) AllocAutoID(ctx context.Context, req *AutoIDRequest) (*AutoIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocAutoID not implemented")
}
func (*UnimplementedAutoIDAllocServer) Rebase(ctx context.Context, req *RebaseRequest) (*RebaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rebase not implemented")
}

func RegisterAutoIDAllocServer(s *grpc.Server, srv AutoIDAllocServer) {
	s.RegisterService(&_AutoIDAlloc_serviceDesc, srv)
}

func _AutoIDAlloc_AllocAutoID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoIDAllocServer).AllocAutoID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autoid.AutoIDAlloc/AllocAutoID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoIDAllocServer).AllocAutoID(ctx, req.(*AutoIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoIDAlloc_Rebase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoIDAllocServer).Rebase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autoid.AutoIDAlloc/Rebase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoIDAllocServer).Rebase(ctx, req.(*RebaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AutoIDAlloc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "autoid.AutoIDAlloc",
	HandlerType: (*AutoIDAllocServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocAutoID",
			Handler:    _AutoIDAlloc_AllocAutoID_Handler,
		},
		{
			MethodName: "Rebase",
			Handler:    _AutoIDAlloc_Rebase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoid.proto",
}

func (m *AutoIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AutoIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AutoIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Keyspace != nil {
		{
			size := m.Keyspace.Size()
			i -= size
			if _, err := m.Keyspace.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Offset != 0 {
		i = encodeVarintAutoid(dAtA, i, uint64(m.Offset))
		i--
		dAtA[i] = 0x30
	}
	if m.Increment != 0 {
		i = encodeVarintAutoid(dAtA, i, uint64(m.Increment))
		i--
		dAtA[i] = 0x28
	}
	if m.N != 0 {
		i = encodeVarintAutoid(dAtA, i, uint64(m.N))
		i--
		dAtA[i] = 0x20
	}
	if m.IsUnsigned {
		i--
		if m.IsUnsigned {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.TblID != 0 {
		i = encodeVarintAutoid(dAtA, i, uint64(m.TblID))
		i--
		dAtA[i] = 0x10
	}
	if m.DbID != 0 {
		i = encodeVarintAutoid(dAtA, i, uint64(m.DbID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AutoIDRequest_KeyspaceID) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AutoIDRequest_KeyspaceID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintAutoid(dAtA, i, uint64(m.KeyspaceID))
	i--
	dAtA[i] = 0x38
	return len(dAtA) - i, nil
}
func (m *AutoIDRequest_KeyspaceIdentity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AutoIDRequest_KeyspaceIdentity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.KeyspaceIdentity != nil {
		{
			size, err := m.KeyspaceIdentity.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAutoid(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	return len(dAtA) - i, nil
}
func (m *AutoIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AutoIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AutoIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Errmsg) > 0 {
		i -= len(m.Errmsg)
		copy(dAtA[i:], m.Errmsg)
		i = encodeVarintAutoid(dAtA, i, uint64(len(m.Errmsg)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Max != 0 {
		i = encodeVarintAutoid(dAtA, i, uint64(m.Max))
		i--
		dAtA[i] = 0x10
	}
	if m.Min != 0 {
		i = encodeVarintAutoid(dAtA, i, uint64(m.Min))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RebaseRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RebaseRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RebaseRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Keyspace != nil {
		{
			size := m.Keyspace.Size()
			i -= size
			if _, err := m.Keyspace.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Force {
		i--
		if m.Force {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Base != 0 {
		i = encodeVarintAutoid(dAtA, i, uint64(m.Base))
		i--
		dAtA[i] = 0x20
	}
	if m.IsUnsigned {
		i--
		if m.IsUnsigned {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.TblID != 0 {
		i = encodeVarintAutoid(dAtA, i, uint64(m.TblID))
		i--
		dAtA[i] = 0x10
	}
	if m.DbID != 0 {
		i = encodeVarintAutoid(dAtA, i, uint64(m.DbID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RebaseRequest_KeyspaceID) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RebaseRequest_KeyspaceID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintAutoid(dAtA, i, uint64(m.KeyspaceID))
	i--
	dAtA[i] = 0x30
	return len(dAtA) - i, nil
}
func (m *RebaseRequest_KeyspaceIdentity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RebaseRequest_KeyspaceIdentity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.KeyspaceIdentity != nil {
		{
			size, err := m.KeyspaceIdentity.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAutoid(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	return len(dAtA) - i, nil
}
func (m *RebaseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RebaseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RebaseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Errmsg) > 0 {
		i -= len(m.Errmsg)
		copy(dAtA[i:], m.Errmsg)
		i = encodeVarintAutoid(dAtA, i, uint64(len(m.Errmsg)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAutoid(dAtA []byte, offset int, v uint64) int {
	offset -= sovAutoid(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AutoIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DbID != 0 {
		n += 1 + sovAutoid(uint64(m.DbID))
	}
	if m.TblID != 0 {
		n += 1 + sovAutoid(uint64(m.TblID))
	}
	if m.IsUnsigned {
		n += 2
	}
	if m.N != 0 {
		n += 1 + sovAutoid(uint64(m.N))
	}
	if m.Increment != 0 {
		n += 1 + sovAutoid(uint64(m.Increment))
	}
	if m.Offset != 0 {
		n += 1 + sovAutoid(uint64(m.Offset))
	}
	if m.Keyspace != nil {
		n += m.Keyspace.Size()
	}
	return n
}

func (m *AutoIDRequest_KeyspaceID) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovAutoid(uint64(m.KeyspaceID))
	return n
}
func (m *AutoIDRequest_KeyspaceIdentity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.KeyspaceIdentity != nil {
		l = m.KeyspaceIdentity.Size()
		n += 1 + l + sovAutoid(uint64(l))
	}
	return n
}
func (m *AutoIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Min != 0 {
		n += 1 + sovAutoid(uint64(m.Min))
	}
	if m.Max != 0 {
		n += 1 + sovAutoid(uint64(m.Max))
	}
	l = len(m.Errmsg)
	if l > 0 {
		n += 1 + l + sovAutoid(uint64(l))
	}
	return n
}

func (m *RebaseRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DbID != 0 {
		n += 1 + sovAutoid(uint64(m.DbID))
	}
	if m.TblID != 0 {
		n += 1 + sovAutoid(uint64(m.TblID))
	}
	if m.IsUnsigned {
		n += 2
	}
	if m.Base != 0 {
		n += 1 + sovAutoid(uint64(m.Base))
	}
	if m.Force {
		n += 2
	}
	if m.Keyspace != nil {
		n += m.Keyspace.Size()
	}
	return n
}

func (m *RebaseRequest_KeyspaceID) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovAutoid(uint64(m.KeyspaceID))
	return n
}
func (m *RebaseRequest_KeyspaceIdentity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.KeyspaceIdentity != nil {
		l = m.KeyspaceIdentity.Size()
		n += 1 + l + sovAutoid(uint64(l))
	}
	return n
}
func (m *RebaseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Errmsg)
	if l > 0 {
		n += 1 + l + sovAutoid(uint64(l))
	}
	return n
}

func sovAutoid(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAutoid(x uint64) (n int) {
	return sovAutoid(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AutoIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAutoid
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AutoIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AutoIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DbID", wireType)
			}
			m.DbID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DbID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TblID", wireType)
			}
			m.TblID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TblID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsUnsigned", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsUnsigned = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field N", wireType)
			}
			m.N = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.N |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Increment", wireType)
			}
			m.Increment = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Increment |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			m.Offset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Offset |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyspaceID", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Keyspace = &AutoIDRequest_KeyspaceID{v}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyspaceIdentity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAutoid
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAutoid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &apipb.KeyspaceIdentity{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Keyspace = &AutoIDRequest_KeyspaceIdentity{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAutoid(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAutoid
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AutoIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAutoid
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AutoIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AutoIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Min", wireType)
			}
			m.Min = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Min |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Max", wireType)
			}
			m.Max = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Max |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Errmsg", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAutoid
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAutoid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Errmsg = append(m.Errmsg[:0], dAtA[iNdEx:postIndex]...)
			if m.Errmsg == nil {
				m.Errmsg = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAutoid(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAutoid
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RebaseRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAutoid
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RebaseRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RebaseRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DbID", wireType)
			}
			m.DbID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DbID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TblID", wireType)
			}
			m.TblID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TblID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsUnsigned", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsUnsigned = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Base", wireType)
			}
			m.Base = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Base |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Force", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Force = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyspaceID", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Keyspace = &RebaseRequest_KeyspaceID{v}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyspaceIdentity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAutoid
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAutoid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &apipb.KeyspaceIdentity{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Keyspace = &RebaseRequest_KeyspaceIdentity{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAutoid(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAutoid
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RebaseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAutoid
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RebaseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RebaseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Errmsg", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAutoid
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAutoid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Errmsg = append(m.Errmsg[:0], dAtA[iNdEx:postIndex]...)
			if m.Errmsg == nil {
				m.Errmsg = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAutoid(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAutoid
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAutoid(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAutoid
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAutoid
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAutoid
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAutoid
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAutoid
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAutoid        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAutoid          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAutoid = fmt.Errorf("proto: unexpected end of group")
)
