// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: apipb.proto

package apipb

import (
	"fmt"
	"io"
	"math"
	math_bits "math/bits"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// KeyspaceIdentity identifies a V3 tenant keyspace.
//
// For V3 tenant-scoped APIs, namespace_id must be non-zero and keyspace_id must
// satisfy 0 < keyspace_id < 2^24. Namespace 0 and keyspace 0 mean
// missing/invalid identity and must be rejected by V3 validators.
type KeyspaceIdentity struct {
	NamespaceId uint32 `protobuf:"varint,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	KeyspaceId  uint32 `protobuf:"varint,2,opt,name=keyspace_id,json=keyspaceId,proto3" json:"keyspace_id,omitempty"`
}

func (m *KeyspaceIdentity) Reset()         { *m = KeyspaceIdentity{} }
func (m *KeyspaceIdentity) String() string { return proto.CompactTextString(m) }
func (*KeyspaceIdentity) ProtoMessage()    {}
func (*KeyspaceIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9e7a215cfa1dda6, []int{0}
}
func (m *KeyspaceIdentity) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyspaceIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyspaceIdentity.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyspaceIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyspaceIdentity.Merge(m, src)
}
func (m *KeyspaceIdentity) XXX_Size() int {
	return m.Size()
}
func (m *KeyspaceIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyspaceIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_KeyspaceIdentity proto.InternalMessageInfo

func (m *KeyspaceIdentity) GetNamespaceId() uint32 {
	if m != nil {
		return m.NamespaceId
	}
	return 0
}

func (m *KeyspaceIdentity) GetKeyspaceId() uint32 {
	if m != nil {
		return m.KeyspaceId
	}
	return 0
}

func init() {
	proto.RegisterType((*KeyspaceIdentity)(nil), "apipb.KeyspaceIdentity")
}

func init() { proto.RegisterFile("apipb.proto", fileDescriptor_d9e7a215cfa1dda6) }

var fileDescriptor_d9e7a215cfa1dda6 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2c, 0xc8, 0x2c,
	0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0x44, 0xd2, 0xf3, 0xd3,
	0xf3, 0xc1, 0x22, 0xfa, 0x20, 0x16, 0x44, 0x52, 0x8a, 0xbf, 0xa8, 0xb4, 0xb8, 0x04, 0xcc, 0x84,
	0x08, 0x28, 0x85, 0x71, 0x09, 0x78, 0xa7, 0x56, 0x16, 0x17, 0x24, 0x26, 0xa7, 0x7a, 0xa6, 0xa4,
	0xe6, 0x95, 0x64, 0x96, 0x54, 0x0a, 0x29, 0x72, 0xf1, 0xe4, 0x25, 0xe6, 0xa6, 0x82, 0x05, 0xe3,
	0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x83, 0xb8, 0xe1, 0x62, 0x9e, 0x29, 0x42, 0xf2,
	0x5c, 0xdc, 0xd9, 0x50, 0x6d, 0x20, 0x15, 0x4c, 0x60, 0x15, 0x5c, 0xd9, 0x70, 0x93, 0x9c, 0x8c,
	0x6e, 0xac, 0xe0, 0x60, 0x3c, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4,
	0x18, 0x27, 0x3c, 0x96, 0x63, 0x98, 0xf1, 0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f,
	0xe5, 0x18, 0xb8, 0x04, 0xf2, 0x8b, 0xd2, 0xf5, 0x4a, 0x32, 0xb3, 0xcb, 0xf4, 0xb2, 0xcb, 0xc0,
	0x6e, 0x49, 0x62, 0x03, 0x53, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0xa1, 0x40, 0xcb,
	0xcf, 0x00, 0x00, 0x00,
}

func (m *KeyspaceIdentity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyspaceIdentity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyspaceIdentity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.KeyspaceId != 0 {
		i = encodeVarintApipb(dAtA, i, uint64(m.KeyspaceId))
		i--
		dAtA[i] = 0x10
	}
	if m.NamespaceId != 0 {
		i = encodeVarintApipb(dAtA, i, uint64(m.NamespaceId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintApipb(dAtA []byte, offset int, v uint64) int {
	offset -= sovApipb(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *KeyspaceIdentity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NamespaceId != 0 {
		n += 1 + sovApipb(uint64(m.NamespaceId))
	}
	if m.KeyspaceId != 0 {
		n += 1 + sovApipb(uint64(m.KeyspaceId))
	}
	return n
}

func sovApipb(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApipb(x uint64) (n int) {
	return sovApipb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *KeyspaceIdentity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApipb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeyspaceIdentity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeyspaceIdentity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NamespaceId", wireType)
			}
			m.NamespaceId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApipb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NamespaceId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyspaceId", wireType)
			}
			m.KeyspaceId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApipb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyspaceId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApipb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApipb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApipb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApipb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApipb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApipb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApipb
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApipb
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApipb
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApipb        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApipb          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApipb = fmt.Errorf("proto: unexpected end of group")
)
