// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: routerpb.proto

package routerpb

import (
	"context"
	"fmt"
	"math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	pdpb "github.com/pingcap/kvproto/pkg/pdpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("routerpb.proto", fileDescriptor_3a7843d531c130ba) }

var fileDescriptor_3a7843d531c130ba = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x4a, 0xc3, 0x40,
	0x14, 0xc6, 0x33, 0x08, 0x25, 0x8e, 0xff, 0xca, 0xa0, 0xd5, 0x06, 0x9c, 0x85, 0x2b, 0x57, 0x51,
	0xea, 0x52, 0x10, 0x0c, 0x62, 0x74, 0xa7, 0xc9, 0x09, 0xda, 0xfa, 0x88, 0xa5, 0x25, 0x13, 0x67,
	0x5e, 0x02, 0xbd, 0x85, 0x4b, 0x8f, 0xe0, 0x51, 0x5c, 0x76, 0xd9, 0xa5, 0x24, 0xa7, 0x70, 0x27,
	0x9d, 0x74, 0x06, 0x89, 0x15, 0xa4, 0xab, 0xbc, 0xf9, 0x7d, 0xdf, 0xfb, 0x31, 0x81, 0xa1, 0xbb,
	0x52, 0xe4, 0x08, 0x32, 0x1b, 0xf8, 0x99, 0x14, 0x28, 0x98, 0x6b, 0xce, 0x1e, 0xcd, 0x9e, 0x0c,
	0xf5, 0xf6, 0x13, 0x91, 0x08, 0x3d, 0x9e, 0x2d, 0xa6, 0x25, 0xdd, 0x93, 0xb9, 0x42, 0x3d, 0xd6,
	0xa0, 0xf7, 0xb5, 0x41, 0x5b, 0x91, 0xde, 0x67, 0x57, 0x74, 0x33, 0x04, 0x8c, 0x20, 0x19, 0x89,
	0x94, 0x75, 0x7c, 0xed, 0xb2, 0x20, 0x82, 0x97, 0x1c, 0x14, 0x7a, 0x87, 0xbf, 0xb8, 0xca, 0x44,
	0xaa, 0xe0, 0xc4, 0x61, 0x01, 0xdd, 0x09, 0x01, 0x1f, 0x24, 0x14, 0xeb, 0x3b, 0x6e, 0xb5, 0xa3,
	0xc6, 0xc1, 0xf4, 0xfe, 0x86, 0x79, 0x8d, 0xee, 0x02, 0xfe, 0xc3, 0x73, 0x47, 0xb7, 0x1e, 0x73,
	0x90, 0xd3, 0xe5, 0x4d, 0x8e, 0xea, 0xe6, 0x0f, 0x64, 0x1c, 0xdd, 0x15, 0x89, 0xb1, 0x9c, 0x92,
	0x73, 0xc2, 0x62, 0xda, 0x0e, 0xfa, 0x38, 0x7c, 0x8e, 0x87, 0xfd, 0xb4, 0x2e, 0x28, 0x76, 0x5c,
	0x2f, 0x35, 0xb9, 0x71, 0xf2, 0xbf, 0x62, 0x7b, 0xbd, 0x4b, 0xea, 0x86, 0x80, 0x31, 0x0a, 0x09,
	0xec, 0xc0, 0xfe, 0x85, 0x3e, 0x1b, 0x49, 0xa7, 0x89, 0xed, 0x72, 0x48, 0xb7, 0x43, 0xc0, 0xeb,
	0xc9, 0x44, 0x07, 0x8a, 0x75, 0x6d, 0xd3, 0x32, 0x23, 0xf1, 0x56, 0x45, 0x46, 0x14, 0xf4, 0xe6,
	0xef, 0x2e, 0xf9, 0x28, 0x39, 0x99, 0x95, 0x9c, 0x7c, 0x96, 0x9c, 0xbc, 0x56, 0xdc, 0x79, 0xab,
	0xb8, 0x33, 0xab, 0xb8, 0x33, 0xaf, 0xb8, 0x43, 0xdb, 0x42, 0x26, 0x3e, 0x8e, 0xc6, 0x85, 0x3f,
	0x2e, 0xf4, 0x7b, 0x19, 0xb4, 0xf4, 0xe7, 0xe2, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x70, 0x31, 0xfc,
	0x2b, 0x85, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouterClient is the client API for Router service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouterClient interface {
	GetRegion(ctx context.Context, in *pdpb.GetRegionRequest, opts ...grpc.CallOption) (*pdpb.GetRegionResponse, error)
	GetPrevRegion(ctx context.Context, in *pdpb.GetRegionRequest, opts ...grpc.CallOption) (*pdpb.GetRegionResponse, error)
	GetRegionByID(ctx context.Context, in *pdpb.GetRegionByIDRequest, opts ...grpc.CallOption) (*pdpb.GetRegionResponse, error)
	QueryRegion(ctx context.Context, opts ...grpc.CallOption) (Router_QueryRegionClient, error)
	BatchScanRegions(ctx context.Context, in *pdpb.BatchScanRegionsRequest, opts ...grpc.CallOption) (*pdpb.BatchScanRegionsResponse, error)
	GetStore(ctx context.Context, in *pdpb.GetStoreRequest, opts ...grpc.CallOption) (*pdpb.GetStoreResponse, error)
	GetAllStores(ctx context.Context, in *pdpb.GetAllStoresRequest, opts ...grpc.CallOption) (*pdpb.GetAllStoresResponse, error)
}

type routerClient struct {
	cc *grpc.ClientConn
}

func NewRouterClient(cc *grpc.ClientConn) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) GetRegion(ctx context.Context, in *pdpb.GetRegionRequest, opts ...grpc.CallOption) (*pdpb.GetRegionResponse, error) {
	out := new(pdpb.GetRegionResponse)
	err := c.cc.Invoke(ctx, "/routerpb.Router/GetRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetPrevRegion(ctx context.Context, in *pdpb.GetRegionRequest, opts ...grpc.CallOption) (*pdpb.GetRegionResponse, error) {
	out := new(pdpb.GetRegionResponse)
	err := c.cc.Invoke(ctx, "/routerpb.Router/GetPrevRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetRegionByID(ctx context.Context, in *pdpb.GetRegionByIDRequest, opts ...grpc.CallOption) (*pdpb.GetRegionResponse, error) {
	out := new(pdpb.GetRegionResponse)
	err := c.cc.Invoke(ctx, "/routerpb.Router/GetRegionByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) QueryRegion(ctx context.Context, opts ...grpc.CallOption) (Router_QueryRegionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Router_serviceDesc.Streams[0], "/routerpb.Router/QueryRegion", opts...)
	if err != nil {
		return nil, err
	}
	x := &routerQueryRegionClient{stream}
	return x, nil
}

type Router_QueryRegionClient interface {
	Send(*pdpb.QueryRegionRequest) error
	Recv() (*pdpb.QueryRegionResponse, error)
	grpc.ClientStream
}

type routerQueryRegionClient struct {
	grpc.ClientStream
}

func (x *routerQueryRegionClient) Send(m *pdpb.QueryRegionRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *routerQueryRegionClient) Recv() (*pdpb.QueryRegionResponse, error) {
	m := new(pdpb.QueryRegionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routerClient) BatchScanRegions(ctx context.Context, in *pdpb.BatchScanRegionsRequest, opts ...grpc.CallOption) (*pdpb.BatchScanRegionsResponse, error) {
	out := new(pdpb.BatchScanRegionsResponse)
	err := c.cc.Invoke(ctx, "/routerpb.Router/BatchScanRegions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetStore(ctx context.Context, in *pdpb.GetStoreRequest, opts ...grpc.CallOption) (*pdpb.GetStoreResponse, error) {
	out := new(pdpb.GetStoreResponse)
	err := c.cc.Invoke(ctx, "/routerpb.Router/GetStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetAllStores(ctx context.Context, in *pdpb.GetAllStoresRequest, opts ...grpc.CallOption) (*pdpb.GetAllStoresResponse, error) {
	out := new(pdpb.GetAllStoresResponse)
	err := c.cc.Invoke(ctx, "/routerpb.Router/GetAllStores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServer is the server API for Router service.
type RouterServer interface {
	GetRegion(context.Context, *pdpb.GetRegionRequest) (*pdpb.GetRegionResponse, error)
	GetPrevRegion(context.Context, *pdpb.GetRegionRequest) (*pdpb.GetRegionResponse, error)
	GetRegionByID(context.Context, *pdpb.GetRegionByIDRequest) (*pdpb.GetRegionResponse, error)
	QueryRegion(Router_QueryRegionServer) error
	BatchScanRegions(context.Context, *pdpb.BatchScanRegionsRequest) (*pdpb.BatchScanRegionsResponse, error)
	GetStore(context.Context, *pdpb.GetStoreRequest) (*pdpb.GetStoreResponse, error)
	GetAllStores(context.Context, *pdpb.GetAllStoresRequest) (*pdpb.GetAllStoresResponse, error)
}

// UnimplementedRouterServer can be embedded to have forward compatible implementations.
type UnimplementedRouterServer struct {
}

func (*UnimplementedRouterServer) GetRegion(ctx context.Context, req *pdpb.GetRegionRequest) (*pdpb.GetRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegion not implemented")
}
func (*UnimplementedRouterServer) GetPrevRegion(ctx context.Context, req *pdpb.GetRegionRequest) (*pdpb.GetRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrevRegion not implemented")
}
func (*UnimplementedRouterServer) GetRegionByID(ctx context.Context, req *pdpb.GetRegionByIDRequest) (*pdpb.GetRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegionByID not implemented")
}
func (*UnimplementedRouterServer) QueryRegion(srv Router_QueryRegionServer) error {
	return status.Errorf(codes.Unimplemented, "method QueryRegion not implemented")
}
func (*UnimplementedRouterServer) BatchScanRegions(ctx context.Context, req *pdpb.BatchScanRegionsRequest) (*pdpb.BatchScanRegionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchScanRegions not implemented")
}
func (*UnimplementedRouterServer) GetStore(ctx context.Context, req *pdpb.GetStoreRequest) (*pdpb.GetStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStore not implemented")
}
func (*UnimplementedRouterServer) GetAllStores(ctx context.Context, req *pdpb.GetAllStoresRequest) (*pdpb.GetAllStoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllStores not implemented")
}

func RegisterRouterServer(s *grpc.Server, srv RouterServer) {
	s.RegisterService(&_Router_serviceDesc, srv)
}

func _Router_GetRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pdpb.GetRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routerpb.Router/GetRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetRegion(ctx, req.(*pdpb.GetRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetPrevRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pdpb.GetRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetPrevRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routerpb.Router/GetPrevRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetPrevRegion(ctx, req.(*pdpb.GetRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetRegionByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pdpb.GetRegionByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetRegionByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routerpb.Router/GetRegionByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetRegionByID(ctx, req.(*pdpb.GetRegionByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_QueryRegion_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RouterServer).QueryRegion(&routerQueryRegionServer{stream})
}

type Router_QueryRegionServer interface {
	Send(*pdpb.QueryRegionResponse) error
	Recv() (*pdpb.QueryRegionRequest, error)
	grpc.ServerStream
}

type routerQueryRegionServer struct {
	grpc.ServerStream
}

func (x *routerQueryRegionServer) Send(m *pdpb.QueryRegionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *routerQueryRegionServer) Recv() (*pdpb.QueryRegionRequest, error) {
	m := new(pdpb.QueryRegionRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Router_BatchScanRegions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pdpb.BatchScanRegionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).BatchScanRegions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routerpb.Router/BatchScanRegions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).BatchScanRegions(ctx, req.(*pdpb.BatchScanRegionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pdpb.GetStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routerpb.Router/GetStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetStore(ctx, req.(*pdpb.GetStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetAllStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pdpb.GetAllStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetAllStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routerpb.Router/GetAllStores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetAllStores(ctx, req.(*pdpb.GetAllStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Router_serviceDesc = grpc.ServiceDesc{
	ServiceName: "routerpb.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRegion",
			Handler:    _Router_GetRegion_Handler,
		},
		{
			MethodName: "GetPrevRegion",
			Handler:    _Router_GetPrevRegion_Handler,
		},
		{
			MethodName: "GetRegionByID",
			Handler:    _Router_GetRegionByID_Handler,
		},
		{
			MethodName: "BatchScanRegions",
			Handler:    _Router_BatchScanRegions_Handler,
		},
		{
			MethodName: "GetStore",
			Handler:    _Router_GetStore_Handler,
		},
		{
			MethodName: "GetAllStores",
			Handler:    _Router_GetAllStores_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryRegion",
			Handler:       _Router_QueryRegion_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "routerpb.proto",
}
